-- LOOTFORM Manual Top-Up Review
-- Date: 2026-08-25
--
-- Purpose:
--   Real (non-TEST) token top-up flow: player picks an Admin-configured
--   package, transfers via bank/QR shown by the app, uploads a payment
--   slip, and an Admin reviews the slip and approves/rejects the order.
--   Approval credits the wallet atomically; nothing is auto-credited on
--   upload — the client never controls its own balance.
--
-- IMPORTANT:
--   Run this AFTER 202608250001_atomic_craft.sql (reuses its
--   craft_requests-style "atomic money operation" pattern for the
--   review RPC).
--
--   topup_orders already exists in this project (created outside this
--   repo's migrations) with columns:
--   id, reference, user_id, package_code, amount_thb, token_amount,
--   status, payment_method, provider_reference, environment_mode,
--   created_at, paid_at, updated_at
--   This migration only ADDs columns to it.

BEGIN;

/* =========================================================
   1. TOP-UP SETTINGS (singleton row, Admin-configured)
========================================================= */

CREATE TABLE IF NOT EXISTS public.topup_settings (
  id int PRIMARY KEY DEFAULT 1,
  bank_name text NOT NULL DEFAULT '',
  bank_account_name text NOT NULL DEFAULT '',
  bank_account_number text NOT NULL DEFAULT '',
  qr_image_url text,
  qr_image_path text,
  rate_lt_per_thb numeric NOT NULL DEFAULT 1 CHECK (rate_lt_per_thb > 0),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT topup_settings_singleton CHECK (id = 1)
);

INSERT INTO public.topup_settings (id)
VALUES (1)
ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.topup_settings ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.topup_settings FROM PUBLIC;
REVOKE ALL ON TABLE public.topup_settings FROM anon;
REVOKE ALL ON TABLE public.topup_settings FROM authenticated;
GRANT ALL ON TABLE public.topup_settings TO service_role;

/* =========================================================
   2. TOP-UP PACKAGES (Admin-configured list)
========================================================= */

CREATE TABLE IF NOT EXISTS public.topup_packages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  amount_thb numeric NOT NULL CHECK (amount_thb > 0),
  label text,
  is_active boolean NOT NULL DEFAULT true,
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.topup_packages ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.topup_packages FROM PUBLIC;
REVOKE ALL ON TABLE public.topup_packages FROM anon;
REVOKE ALL ON TABLE public.topup_packages FROM authenticated;
GRANT ALL ON TABLE public.topup_packages TO service_role;

/* =========================================================
   3. EXTEND topup_orders
========================================================= */

ALTER TABLE public.topup_orders
  ADD COLUMN IF NOT EXISTS package_id bigint REFERENCES public.topup_packages(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS rate_lt_per_thb_snapshot numeric,
  ADD COLUMN IF NOT EXISTS slip_image_url text,
  ADD COLUMN IF NOT EXISTS slip_image_path text,
  ADD COLUMN IF NOT EXISTS reviewed_by uuid,
  ADD COLUMN IF NOT EXISTS reviewed_at timestamptz,
  ADD COLUMN IF NOT EXISTS reject_reason text;

/* =========================================================
   4. ATOMIC REVIEW (APPROVE credits wallet, REJECT does not)
========================================================= */

CREATE OR REPLACE FUNCTION public.topup_review_atomic(
  p_order_id bigint,
  p_admin_id uuid,
  p_action text,
  p_reject_reason text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_order public.topup_orders%ROWTYPE;
  v_wallet public.wallets%ROWTYPE;
  v_response jsonb;
BEGIN
  IF p_action NOT IN ('APPROVE', 'REJECT') THEN
    RAISE EXCEPTION 'LOOTFORM_TOPUP_INVALID_ACTION'
      USING ERRCODE = 'P0001';
  END IF;

  SELECT *
  INTO v_order
  FROM public.topup_orders
  WHERE id = p_order_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'LOOTFORM_TOPUP_ORDER_NOT_FOUND'
      USING ERRCODE = 'P0001';
  END IF;

  IF v_order.status <> 'PENDING' THEN
    RAISE EXCEPTION 'LOOTFORM_TOPUP_ALREADY_REVIEWED'
      USING ERRCODE = 'P0001';
  END IF;

  IF p_action = 'APPROVE' THEN
    SELECT *
    INTO v_wallet
    FROM public.wallets
    WHERE user_id = v_order.user_id
    FOR UPDATE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'LOOTFORM_WALLET_NOT_FOUND'
        USING ERRCODE = 'P0001';
    END IF;

    UPDATE public.wallets
    SET
      balance = balance + v_order.token_amount,
      updated_at = now()
    WHERE user_id = v_order.user_id
    RETURNING *
    INTO v_wallet;

    INSERT INTO public.wallet_transactions (
      user_id,
      type,
      amount,
      description,
      item_id,
      environment_mode
    )
    VALUES (
      v_order.user_id,
      'TOPUP',
      v_order.token_amount,
      concat_ws(' / ', 'TOPUP', v_order.reference, v_order.amount_thb || ' THB'),
      NULL,
      v_order.environment_mode
    );

    UPDATE public.topup_orders
    SET
      status = 'PAID',
      paid_at = now(),
      reviewed_by = p_admin_id,
      reviewed_at = now(),
      reject_reason = NULL,
      updated_at = now()
    WHERE id = p_order_id
    RETURNING *
    INTO v_order;

    v_response := jsonb_build_object(
      'order', to_jsonb(v_order),
      'wallet_balance', v_wallet.balance
    );
  ELSE
    IF COALESCE(BTRIM(p_reject_reason), '') = '' THEN
      RAISE EXCEPTION 'LOOTFORM_TOPUP_REJECT_REASON_REQUIRED'
        USING ERRCODE = 'P0001';
    END IF;

    UPDATE public.topup_orders
    SET
      status = 'REJECTED',
      reviewed_by = p_admin_id,
      reviewed_at = now(),
      reject_reason = p_reject_reason,
      updated_at = now()
    WHERE id = p_order_id
    RETURNING *
    INTO v_order;

    v_response := jsonb_build_object(
      'order', to_jsonb(v_order),
      'wallet_balance', NULL
    );
  END IF;

  RETURN v_response;
END;
$$;

REVOKE ALL ON FUNCTION public.topup_review_atomic(bigint, uuid, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.topup_review_atomic(bigint, uuid, text, text) FROM anon;
REVOKE ALL ON FUNCTION public.topup_review_atomic(bigint, uuid, text, text) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.topup_review_atomic(bigint, uuid, text, text) TO service_role;

COMMIT;
