-- LOOTFORM Plain Shop (direct buy, no Craft grade roll)
-- Date: 2026-09-03
--
-- Purpose:
--   A second, parallel purchase path alongside Craft: browse a plain
--   THB-priced catalog (shop_items), pick exactly what you get (no
--   server-side grade roll), pay via bank transfer + slip upload, an
--   Admin reviews and approves -- same manual-review trust model as
--   202608252000_manual_topup_review.sql, just for physical goods
--   instead of an LT top-up. Kept deliberately separate from
--   products/product_designs/items (those are wired to the season +
--   grade-roll system) so this never needs a fake "grade" value.
--
-- NOT YET APPLIED to the live project -- saved locally for review/testing.

BEGIN;

/* =========================================================
   0. STORAGE BUCKETS
      - shop-order-slips: private, mirrors topup-slips exactly
      - shop-images: public, mirrors product-images exactly
========================================================= */

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('shop-order-slips', 'shop-order-slips', false, 5242880, ARRAY['image/jpeg', 'image/png', 'image/webp'])
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('shop-images', 'shop-images', true, 5242880, ARRAY['image/jpeg', 'image/png', 'image/webp'])
ON CONFLICT (id) DO NOTHING;

/* =========================================================
   1. SHOP ITEMS (Admin-managed plain catalog)
========================================================= */

CREATE TABLE IF NOT EXISTS public.shop_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  category text NOT NULL,
  description text,
  price_thb numeric NOT NULL CHECK (price_thb > 0),
  available_sizes text[] NOT NULL DEFAULT '{}',
  image_url text,
  sort_order int NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.shop_items ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.shop_items FROM PUBLIC;
REVOKE ALL ON TABLE public.shop_items FROM anon;
REVOKE ALL ON TABLE public.shop_items FROM authenticated;
GRANT SELECT ON TABLE public.shop_items TO anon;
GRANT SELECT ON TABLE public.shop_items TO authenticated;
GRANT ALL ON TABLE public.shop_items TO service_role;

DROP POLICY IF EXISTS shop_items_read_active ON public.shop_items;
CREATE POLICY shop_items_read_active
  ON public.shop_items
  FOR SELECT
  TO anon, authenticated
  USING (is_active = true);

/* =========================================================
   2. SHOP ORDERS
========================================================= */

CREATE TABLE IF NOT EXISTS public.shop_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  shop_item_id bigint NOT NULL REFERENCES public.shop_items(id),

  item_name_snapshot text NOT NULL,
  price_thb_snapshot numeric NOT NULL,

  size text,
  quantity int NOT NULL DEFAULT 1 CHECK (quantity > 0),
  total_thb numeric NOT NULL CHECK (total_thb > 0),

  shipping_address_id bigint REFERENCES public.shipping_addresses(id),

  reference text NOT NULL UNIQUE,
  slip_image_path text NOT NULL,
  status text NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),

  reviewed_by uuid,
  reviewed_at timestamptz,
  reject_reason text,

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.shop_orders ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.shop_orders FROM PUBLIC;
REVOKE ALL ON TABLE public.shop_orders FROM anon;
REVOKE ALL ON TABLE public.shop_orders FROM authenticated;
GRANT SELECT, INSERT ON TABLE public.shop_orders TO authenticated;
GRANT ALL ON TABLE public.shop_orders TO service_role;

DROP POLICY IF EXISTS shop_orders_read_own ON public.shop_orders;
CREATE POLICY shop_orders_read_own
  ON public.shop_orders
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS shop_orders_insert_own ON public.shop_orders;
CREATE POLICY shop_orders_insert_own
  ON public.shop_orders
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

-- No UPDATE policy for authenticated/anon on purpose: review only
-- happens through shop_order_review_atomic() below (service_role).

/* =========================================================
   3. ATOMIC REVIEW (APPROVE / REJECT -- no wallet/ledger writes)
========================================================= */

CREATE OR REPLACE FUNCTION public.shop_order_review_atomic(
  p_order_id bigint,
  p_admin_id uuid,
  p_action text,
  p_reject_reason text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_order public.shop_orders%ROWTYPE;
BEGIN
  IF p_action NOT IN ('APPROVE', 'REJECT') THEN
    RAISE EXCEPTION 'LOOTFORM_SHOP_ORDER_INVALID_ACTION'
      USING ERRCODE = 'P0001';
  END IF;

  SELECT *
  INTO v_order
  FROM public.shop_orders
  WHERE id = p_order_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'LOOTFORM_SHOP_ORDER_NOT_FOUND'
      USING ERRCODE = 'P0001';
  END IF;

  IF v_order.status <> 'PENDING' THEN
    RAISE EXCEPTION 'LOOTFORM_SHOP_ORDER_ALREADY_REVIEWED'
      USING ERRCODE = 'P0001';
  END IF;

  IF p_action = 'APPROVE' THEN
    UPDATE public.shop_orders
    SET
      status = 'APPROVED',
      reviewed_by = p_admin_id,
      reviewed_at = now(),
      reject_reason = NULL,
      updated_at = now()
    WHERE id = p_order_id
    RETURNING *
    INTO v_order;
  ELSE
    IF COALESCE(BTRIM(p_reject_reason), '') = '' THEN
      RAISE EXCEPTION 'LOOTFORM_SHOP_ORDER_REJECT_REASON_REQUIRED'
        USING ERRCODE = 'P0001';
    END IF;

    UPDATE public.shop_orders
    SET
      status = 'REJECTED',
      reviewed_by = p_admin_id,
      reviewed_at = now(),
      reject_reason = p_reject_reason,
      updated_at = now()
    WHERE id = p_order_id
    RETURNING *
    INTO v_order;
  END IF;

  RETURN jsonb_build_object('order', to_jsonb(v_order));
END;
$$;

REVOKE ALL ON FUNCTION public.shop_order_review_atomic(bigint, uuid, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.shop_order_review_atomic(bigint, uuid, text, text) FROM anon;
REVOKE ALL ON FUNCTION public.shop_order_review_atomic(bigint, uuid, text, text) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.shop_order_review_atomic(bigint, uuid, text, text) TO service_role;

COMMIT;
